### PR TITLE
Add a retry logic to docker login operation

### PR DESCRIPTION
**Pull request by enescakir**
While there's an existing retry mechanism for the `docker pull` command [^1], it's missing for `docker login`.

Similar to the `docker pull` scenario, the container registry could potentially be briefly unavailable or inaccessible, leading to failed `docker login` attempt and subsequent workflow run failures.

Since it's container based workflow, there is not way to retry on customer side. The runner should retry itself.

It also aligns with community feedback [^2].

[^1]: https://github.com/actions/runner/blob/8e0cd36cd8c74c3067ffe10189c1e42f7e753af2/src/Runner.Worker/ContainerOperationProvider.cs#L201
[^2]: https://github.com/orgs/community/discussions/73069

### CODE REVIEW

**Review by mikebowyer — APPROVED** [review]

**Review by bazy84 — APPROVED** [review]

**Review by simonatbosch — APPROVED** [review]

**Comment by igwejk** [comment]
Hi @enescakir, this probably fell through the crack. I'm doing something about getting attention to it.

**Comment by enescakir** [comment]
> Hi @enescakir, this probably fell through the crack. I'm doing something about getting attention to it.

It seems that contributors primarily review each other's pull requests. Pull requests from the community don't receive much attention. What can I do to gain more visibility?

**Review by nikola-jokic — APPROVED** [review]
LGTM

**Comment by igwejk** [comment]
@enescakir quite visible now 🙂

**Comment by igwejk** [comment]
@nikola-jokic shall we merge this PR already?

**Review by thboop — APPROVED** [review]
lgtm

**Comment by thboop** [comment]
Thanks for the contribution @enescakir, I'm going to go ahead and merge this pr, it should roll out with the next runner release, which should be within the next couple weeks

**Pull request merged**
