### PR TITLE
use /usr/bin/env to find bash in scripts

### PR DESCRIPTION
**Pull request by mmahut**
This changes uses the ```/usr/bin/env``` utility to find the location of bash in scripts. 

Right now, the scripts are assuming the location of ```bash``` which might not be true on some systems such as NixOS and others.

For more information, please see https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Is there an issue logged for this?

**Comment by mmahut** [comment]
@bryanmacfarlane I do not think so.

**Comment by zimbatm** [comment]
@mmahut semi out of topic, I have a WIP PR to make the actions runner on nixos: https://github.com/nix-community/infra/pull/5

**Comment by Mic92** [comment]
With the following shell.nix I was able to build it:

```
with import <nixpkgs> {};
let
  fhs = pkgs.buildFHSUserEnv {
    name = "runner-env";
    targetPkgs = pkgs: with pkgs; [
      dotnet-sdk_3
      icu
    ];
    extraOutputsToInstall = [ "dev" ];
  };
in fhs.env
```

```
nix-shell -p --run 'dotnet msbuild -t:Build -p:PackageRuntime=linux-x64 -p:BUILDCONFIG=Release -p:RunnerVersion=$(cat src/runnerversion) src/dir.proj'
```

**Comment by Mic92** [comment]
It also produces a `_layout/bin/Sdk.deps.json` which could be used to download all nuget dependencies.

**Comment by domenkozar** [comment]
@Mic92 could we also just run actions in that FHS?

**Comment by Mic92** [comment]
> @Mic92 could we also just run actions in that FHS?

Yes. All that should work.

**Comment by nvtkaszpir** [comment]
> Is there an issue logged for this?

#565

**Comment by zimbatm** [comment]
This is still a valid fix

**Comment by Mic92** [comment]
> Is there an issue logged for this?

I created an issue in case this is required for processing the pull request: https://github.com/actions/runner/issues/848

**Review by TingluoHuang — APPROVED** [review]

**Pull request merged**
