### PR TITLE
expose GITHUB_REPOSITORY_OWNER.

### PR DESCRIPTION
**Pull request by TingluoHuang**
https://github.com/github/c2c-actions-runtime/issues/333

launch PR: https://github.com/github/launch/pull/2667

### CODE REVIEW

**Comment by gitfool** [comment]
@TingluoHuang @ericsciple I ran a build with the latest hosted images and runner `v2.168.0`. I now see the `CI` and `GITHUB_JOB` environment variables but I don't see `GITHUB_REPOSITORY_OWNER`:
- [Linux](https://github.com/gitfool/Cake.Dungeon/runs/561120904#step:7:69)
- [Mac](https://github.com/gitfool/Cake.Dungeon/runs/561120902#step:7:69)
- [Windows](https://github.com/gitfool/Cake.Dungeon/runs/561120898#step:7:79)
- [Docker](https://github.com/gitfool/Cake.Dungeon/runs/561123463#step:7:42)

Is there something I'm missing? 🤔

**Comment by gitfool** [comment]
Please let me know if `GITHUB_REPOSITORY_OWNER` should be visible, otherwise I'll need to remove support for it from my [Cake](https://github.com/cake-build/cake) PR.

**Comment by TingluoHuang** [comment]
@gitfool I just tried on my account, I can see the env when I `printenv|sort`
```
GITHUB_REPOSITORY=TingluoHuang/main
GITHUB_REPOSITORY_OWNER=TingluoHuang
```
What's your repository name that not has this env? I can check to see whether this is due to delay in deployment.

**Comment by gitfool** [comment]
@TingluoHuang see my links above showing build logs with env vars for [gitfool/Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon).

**Comment by gitfool** [comment]
@TingluoHuang kicked off another build, same runner `v2.168.0` but this time I see `GITHUB_REPOSITORY_OWNER`. Weird but answers my question. Thanks anyway!

**Pull request merged**
