### PR TITLE
Do not give up if Results is powering logs

### PR DESCRIPTION
**Pull request by yacaovsnc**
Do not give up if Results is powering logs.  Continue to upload the next file in that case.

### CODE REVIEW

**Review by DARKo6o6o6 — APPROVED** [review]

**Comment by DARKo6o6o6** [comment]
You have My permission Sir

**Comment by pje** [comment]
The logical change makes sense to me!

One request: if we're renaming variables, can we do it everywhere all at once? `s/resultService/resultsService/g`

👉 https://github.com/search?q=repo%3Ayacaovsnc%2Frunner%20resultServiceOnly&type=code

**Comment by yacaovsnc** [comment]
Thanks @pje!  I think I got all the name variables.  Grep doesn't show any more instance of the old `ResultServiceOnly` name anymore.  🙇🏼‍♂️

**Comment by pje** [comment]
@yacaovsnc Yep, you're right! I messed up the new search syntax and was looking at the main branch. 🤦 

Looks good! 👍

**Review by pje — APPROVED** [review]

**Pull request merged**
