### PR TITLE
Add github.job_id to context.

### PR DESCRIPTION
**Pull request by TingluoHuang**
https://github.com/github/c2c-actions-runtime/issues/1784

The `github.job_id` will be the `CheckRunId` of the workflow job.

### CODE REVIEW

**Review by cory-miller — APPROVED** [review]

**Comment by qoomon** [comment]
@TingluoHuang why this was never merged? This would solve a lot of issues e.g., https://github.com/orgs/community/discussions/8945#discussioncomment-10431193

**Comment by adamsir-et** [comment]
@TingluoHuang  are we able to re-open this and get this merged? I find if i want to put a URL for a specific job flow - this seems to be the missing point

**Comment by nsmithtt** [comment]
@cory-miller / @TingluoHuang 
This is still an issue and is impacting many people for almost 3 years: https://github.com/orgs/community/discussions/8945

**Comment by rdhar** [comment]
While (hacky) [workarounds exist](https://github.com/orgs/community/discussions/129314), they still fall short of GitHub API delivering a reliable source for the job name. Unfortunately, especially given the job name is treated as a unique identifier, while still being over-writable via `name:` attribute or running jobs in matrix strategy.

**Pull request closed without merging**
