### PR TITLE
Avoid ConsoleColor.White, it is unreadable on light themes (#1295)

### PR DESCRIPTION
**Pull request by ilg-ul**

### CODE REVIEW

**Comment by ilg-ul** [comment]
In the second iteration I removed the explicit setting for White in the banner and the prompt.

**Review by fhammerl — APPROVED** [review]
LGTM!

**Comment by ilg-ul** [comment]
Great, thank you!

**Comment by ilg-ul** [comment]
Oops, I missed the detail that it was not merged yet. Reopened.

**Comment by fhammerl** [comment]
Enabling auto-merge for #5a9543b7123ae009c7918f6deec26a1c4dded98f after checks succeed.

**Pull request merged**
