### PR TITLE
Write archive hash/size to log after extraction error

### PR DESCRIPTION
**Pull request by larsxschneider**
I would like to understand the corrupt archives better. Let's log their size. Maybe this gives us a new clue in what way these archives are corrupted.

⚠️ Untested! How do I test this properly? ⚠️

### CODE REVIEW

**Comment by carlosmn** [comment]
What would help with figuring out if something's gone really wrong on the codeload side would be to store the error message from tar somewhere.

**Comment by AvaStancu** [comment]
@larsxschneider Regarding testing, would extracting the new logic into a separate function that for ex. receives the `archiveFile` and returns the `sha256hash` / `fi.Length`, so you can unit test it, help? what else would you need to add a test?

**Comment by TingluoHuang** [comment]
@larsxschneider I will take over the PR with more changes (ex: send the output from `tar` on failures) and get it tested and merged.

**Comment by TingluoHuang** [comment]
Taking over with https://github.com/actions/runner/pull/2939

**Pull request closed without merging**
