### PR TITLE
Update to .NET Core SDK 3.1.302

### LINKED ISSUE #574: Runner configure step stuck at authenticating when IPv6 is broken
**Describe the bug**

I'm trying to install a Github Actions Runner. When following the instructions it just hangs:

```
bluecmd@runner:~/actions-runner$ ./config.sh --url https://github.com/bluecmd/abc --token xxxxxxx

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

```

**To Reproduce**
1. Run `./config.sh --url https://github.com/bluecmd/abc--token xxx`
2. See output and get stuck.

**Expected behavior**
Configuration is completed as per documentation.

## Runner Version and Platform
v2.169.1

OS of the machine running the runner? OSX/Windows/Linux/...

Debian Testing

## What's not working?
Configure process gets stuck at 'Authentication'

## Job Log Output

N/A

## Runner and Worker's Diagnostic Logs

```
[2020-07-03 22:53:03Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO HostContext] Well known config file 'Credentials': '/home/bluecmd/actions-runner/.credentials'
[2020-07-03 22:53:03Z INFO Listener] Runner is built for Linux (X64) - linux-x64.
[2020-07-03 22:53:03Z INFO Listener] RuntimeInformation: Linux 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24).
[2020-07-03 22:53:03Z INFO Listener] Version: 2.169.1
[2020-07-03 22:53:03Z INFO Listener] Commit: 4f840647b375b65a4efa361abc1b84f783442de6
[2020-07-03 22:53:03Z INFO Listener] Culture: en-US
[2020-07-03 22:53:03Z INFO Listener] UI Culture: en-US
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO Listener] Validating directory permissions for: '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO CommandLineParser] Parse
[2020-07-03 22:53:03Z INFO CommandLineParser] Parsing 5 args
[2020-07-03 22:53:03Z INFO CommandLineParser] parsing argument
[2020-07-03 22:53:03Z INFO CommandLineParser] HasArgs: False
[2020-07-03 22:53:03Z INFO CommandLineParser] Adding Command: configure
[2020-07-03 22:53:03Z INFO CommandLineParser] parsing argument
[2020-07-03 22:53:03Z INFO CommandLineParser] HasArgs: True
[2020-07-03 22:53:03Z INFO CommandLineParser] arg: url
[2020-07-03 22:53:03Z INFO CommandLineParser] parsing argument
[2020-07-03 22:53:03Z INFO CommandLineParser] HasArgs: True
[2020-07-03 22:53:03Z INFO CommandLineParser] Adding option 'url': 'https://github.com/bluecmd/abc'
[2020-07-03 22:53:03Z INFO CommandLineParser] parsing argument
[2020-07-03 22:53:03Z INFO CommandLineParser] HasArgs: True
[2020-07-03 22:53:03Z INFO CommandLineParser] arg: token
[2020-07-03 22:53:03Z INFO CommandLineParser] parsing argument
[2020-07-03 22:53:03Z INFO CommandLineParser] HasArgs: True
[2020-07-03 22:53:03Z INFO CommandLineParser] Adding option 'token': '***'
[2020-07-03 22:53:03Z INFO Listener] Arguments parsed
[2020-07-03 22:53:03Z INFO Runner] ExecuteCommand
[2020-07-03 22:53:03Z INFO ConfigurationStore] currentAssemblyLocation: /home/bluecmd/actions-runner/bin/Runner.Listener.dll
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO ConfigurationStore] binPath: /home/bluecmd/actions-runner/bin
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO ConfigurationStore] RootFolder: /home/bluecmd/actions-runner
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO HostContext] Well known config file 'Runner': '/home/bluecmd/actions-runner/.runner'
[2020-07-03 22:53:03Z INFO ConfigurationStore] ConfigFilePath: /home/bluecmd/actions-runner/.runner
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO HostContext] Well known config file 'Credentials': '/home/bluecmd/actions-runner/.credentials'
[2020-07-03 22:53:03Z INFO ConfigurationStore] CredFilePath: /home/bluecmd/actions-runner/.credentials
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO HostContext] Well known config file 'MigratedCredentials': '/home/bluecmd/actions-runner/.credentials_migrated'
[2020-07-03 22:53:03Z INFO ConfigurationStore] MigratedCredFilePath: /home/bluecmd/actions-runner/.credentials_migrated
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Bin': '/home/bluecmd/actions-runner/bin'
[2020-07-03 22:53:03Z INFO HostContext] Well known directory 'Root': '/home/bluecmd/actions-runner'
[2020-07-03 22:53:03Z INFO HostContext] Well known config file 'Service': '/home/bluecmd/actions-runner/.service'
[2020-07-03 22:53:03Z INFO ConfigurationStore] ServiceConfigFilePath: /home/bluecmd/actions-runner/.service
[2020-07-03 22:53:03Z INFO CommandSettings] Flag 'help': 'False'
[2020-07-03 22:53:03Z INFO CommandSettings] Flag 'version': 'False'
[2020-07-03 22:53:03Z INFO CommandSettings] Flag 'commit': 'False'
[2020-07-03 22:53:03Z INFO CommandSettings] Command 'configure': 'True'
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE:
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |        ____ _ _   _   _       _          _        _   _                      |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |                                                                              |
[2020-07-03 22:53:03Z INFO Terminal] WRITE: |
[2020-07-03 22:53:03Z INFO Terminal] WRITE: Self-hosted runner registration
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE:                         |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: |                                                                              |
[2020-07-03 22:53:03Z INFO Terminal] WRITE LINE: --------------------------------------------------------------------------------
[2020-07-03 22:53:03Z INFO ConfigurationManager] ConfigureAsync
[2020-07-03 22:53:03Z INFO ConfigurationStore] IsConfigured()
[2020-07-03 22:53:03Z INFO ConfigurationStore] IsConfigured: False
[2020-07-03 22:53:03Z INFO ConfigurationManager] Is configured: False
[2020-07-03 22:53:03Z INFO CommandSettings] Arg 'url': 'https://github.com/bluecmd/abc'
[2020-07-03 22:53:03Z INFO CommandSettings] Remove url from Arg dictionary.
[2020-07-03 22:53:03Z INFO CommandSettings] Arg 'token': '***'
[2020-07-03 22:53:03Z INFO CommandSettings] Remove token from Arg dictionary.
[2020-07-03 22:53:03Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration'
[2020-07-03 22:53:03Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2020-07-03 22:53:03Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2020-07-03 22:53:03Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:53:03Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2020-07-03 22:53:03Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:53:03Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2020-07-03 22:53:03Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:54:03Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/xxxxxxxxxxxx/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2020-07-03 22:54:03Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/xxxxxxxxxxxx/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2020-07-03 22:54:03Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-07-03 22:54:03Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-07-03 22:54:03Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:54:03Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:54:43Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/xxxxxxxxxxxx/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2020-07-03 22:54:43Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-07-03 22:54:43Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:55:03Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/xxxxxxxxxxxx/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2020-07-03 22:55:03Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-07-03 22:55:03Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/xxxxxxxxxxxx/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2020-07-03 22:55:03Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2020-07-03 22:55:03Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2020-07-03 22:55:03Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2020-07-03 22:55:03Z ERR  RunnerServer] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
[2020-07-03 22:55:03Z ERR  RunnerServer] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerServer.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
[2020-07-03 22:55:03Z ERR  RunnerServer] #####################################################
[2020-07-03 22:55:03Z ERR  RunnerServer] #####################################################
[2020-07-03 22:55:03Z ERR  RunnerServer] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-07-03 22:55:03Z ERR  RunnerServer] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2020-07-03 22:55:04Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:55:04Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2020-07-03 22:55:30Z INFO Terminal] WRITE LINE: Exiting...
```

I also tried to manually ensure I can connect to the URL in question:

```
bluecmd@runner:~/actions-runner$ curl https://pipelines.actions.githubusercontent.com/ -v
*   Trying 2620:1ec:21::16:443...
* TCP_NODELAY set
*   Trying 13.107.42.16:443...
* TCP_NODELAY set
* Connected to pipelines.actions.githubusercontent.com (13.107.42.16) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.actions.githubusercontent.com
*  start date: Apr  3 00:00:00 2020 GMT
*  expire date: Apr  8 12:00:00 2022 GMT
*  subjectAltName: host "pipelines.actions.githubusercontent.com" matched cert's "*.actions.githubusercontent.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56010e4e7e30)
> GET / HTTP/2
> Host: pipelines.actions.githubusercontent.com
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404
< strict-transport-security: max-age=2592000
< x-tfs-processid: a90ee006-9f99-4d9f-afff-262224c9779b
< activityid: 5aff2c55-9df5-400d-9b80-ceb1761e6e3a
< x-tfs-session: 5aff2c55-9df5-400d-9b80-ceb1761e6e3a
< x-vss-e2eid: 5aff2c55-9df5-400d-9b80-ceb1761e6e3a
< x-vss-senderdeploymentid: a07ab14e-025a-39c3-8d53-788cd7ce207f
< x-msedge-ref: Ref A: 484DB8CE81A94FA5A1BAD98BF0CBE352 Ref B: STOEDGE0913 Ref C: 2020-07-03T22:58:33Z
< date: Fri, 03 Jul 2020 22:58:33 GMT
< content-length: 0
<
* Connection #0 to host pipelines.actions.githubusercontent.com left intact
```

Doing a curl `-6` fails, and I discovered a routing issue in my IPv6 setup. Fixing that made the configuration succeed, however it was a real pain to find any debug information on what was going on.

I suggest the runner should try on both v4 and v6 - or at least report that it cannot connect instead of just freezing.

### PR DESCRIPTION
**Pull request by fabianishere**
This change updates the .NET Core SDK used by the Actions Runner to
version 3.1.302 to address the issues that are caused by the following issue:
    https://github.com/dotnet/runtime/issues/13475
See #574 for more information.

Fixes #574

### CODE REVIEW

**Review by Laaknor — APPROVED** [review]
Seems to work for me.

**Review by McSam94 — APPROVED** [review]

**Comment by fabianishere** [comment]
@TingluoHuang  @ericsciple 

Could you please consider this pull request? This solves a pretty serious issue with the current builds and prevents Github Actions from working within a container (as https://github.com/dotnet/runtime/issues/13475 explains).

**Review by TingluoHuang — APPROVED** [review]

**Review by TingluoHuang — APPROVED** [review]

**Comment by meiswjn** [comment]
When will this be released?

**Comment by brandan-schmitz** [comment]
And word on when this can get pulled into the master and released?

**Pull request merged**
