### PR TITLE
Support action.yaml file

### PR DESCRIPTION
**Pull request by gimenete**
👋 Actions experience engineer here.

We did all the work in dotcom to support `actions.yaml` besides `action.yml` but I forgot to mention that for the runner side. Since it was a small change I decided to open a PR :)

### CODE REVIEW

**Comment by TingluoHuang** [comment]
@gimenete any ADR or issue i can reference? 😄

**Comment by gimenete** [comment]
@TingluoHuang yep, sorry:

https://github.com/github/c2c-actions-experience/issues/1459
https://github.com/github/help-docs/issues/11950

**Comment by TingluoHuang** [comment]
@gimenete do you mind add some L0 test for this? you can find some sample L0 test from https://github.com/actions/runner/blob/master/src/Test/L0/Worker/ActionManagerL0.cs

Or I can help you add them after you merge, the change LGTM

**Comment by gimenete** [comment]
@TingluoHuang Sure, I'll try to write one on Monday. I'm travelling today :)

**Pull request merged**
