### PR TITLE
chore(Dockerfile): update Dockerfile to support multiple architectures

### PR DESCRIPTION
**Pull request by kahirokunn**
Usage

```sh
docker buildx build --build-arg RUNNER_VERSION=2.304.0 --platform linux/amd64,linux/arm64 --output=type=image,push=true . -t quay.io/actions/actions-runner:latest
```

Build and push I would like to provide a multiple architecture supported image using buildx in Docker image.

The image I built is below.
If you want to try it out, please do so!

```
quay.io/kahirokunn/actions-runner-multi-arch-base:latest
```

### CODE REVIEW

**Comment by kahirokunn** [comment]
@nikola-jokic Could you please review it?

**Comment by nikola-jokic** [comment]
Hey @kahirokunn,

This change looks good to me. But we also need to align on the way we publish images built on different architectures :relaxed: We will keep you posted on this topic

**Comment by kahirokunn** [comment]
Okay 👌

**Comment by kahirokunn** [comment]
@nikola-jokic I wanted to accomplish this one, but another person had completed the response, so I will close this one. 😢 
https://github.com/actions/runner/pull/2601

**Comment by nikola-jokic** [comment]
Thank you for doing it anyway!

**Pull request closed without merging**
