### PR TITLE
default post-job action's condition to always().

### PR DESCRIPTION
**Pull request by TingluoHuang**
fix: #292

### CODE REVIEW

**Comment by ericsciple** [comment]
shouldnt it only run if the main ran?

**Comment by ericsciple** [comment]
or, i guess sometimes there might not be a main?

**Comment by TingluoHuang** [comment]
Post get added to step list only when its main pass condition check and about to run.

**Comment by ericsciple** [comment]
Cool. I think this change is good then.

One more thing to think about, which i think is OK... When a run is queued, the server adjust all job/step conditions when none of the status functions are mentioned. So if the condition is `github.event == 'foo'` then it gets adjusted to `success() && (github.event == 'foo')`.

I don't think that type of adjustment is needed for the POST, in fact i think it would be opposite of what we want. So i think they way you have the code in this PR is good. Just something to think through since it's a little tricky - make sure i didnt make a mistake in my mental logic.

**Pull request merged**
